const NEW_PRODUCTS_ADDITIONAL = [
  // OFFICE CHAIRS from images/additional/20 chairs/ (IDs 41-60)
  {
    id: 41,
    name: "Alefjaell Office Chair Grann Golden Brown",
    category: "office-chairs",
    price: 12500,
    material: "Fabric",
    rating: 4.5,
    reviews: 23,
    img: "images/additional/20 chairs/alefjaell-office-chair-grann-golden-brown__0724709_pe734591_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 42,
    name: "Eldberget Malskaer Swivel Chair Beige White",
    category: "office-chairs",
    price: 14900,
    material: "Fabric",
    rating: 4.7,
    reviews: 34,
    img: "images/additional/20 chairs/eldberget-malskaer-swivel-chair-beige-white__1077158_pe856906_s5.jpg",
    badge: "NEW",
    badgeClass: "badge-yellow",
  },
  {
    id: 43,
    name: "Ensholm Chair Green Outdoor",
    category: "office-chairs",
    price: 8900,
    material: "Rattan",
    rating: 4.3,
    reviews: 18,
    img: "images/additional/20 chairs/ensholm-chair-green-outdoor__1236722_pe917719_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 44,
    name: "Fejan Chair Outdoor Foldable White",
    category: "office-chairs",
    price: 4500,
    material: "Plastic",
    rating: 4.2,
    reviews: 56,
    img: "images/additional/20 chairs/fejan-chair-outdoor-foldable-white__0728344_pe736190_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 45,
    name: "Flintan Office Chair Beige",
    category: "office-chairs",
    price: 11900,
    material: "Mesh",
    rating: 4.6,
    reviews: 45,
    img: "images/additional/20 chairs/flintan-office-chair-beige__1007198_pe825954_s5.jpg",
    badge: "BEST SELLER",
    badgeClass: "badge-blue",
  },
  {
    id: 46,
    name: "Gaevle Chair Diseroed Gray",
    category: "office-chairs",
    price: 9500,
    material: "Fabric",
    rating: 4.4,
    reviews: 29,
    img: "images/additional/20 chairs/gaevle-chair-diseroed-gray__1322772_pe942230_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 47,
    name: "Huvudspelare Gaming Chair Black",
    category: "office-chairs",
    price: 18900,
    material: "PU Leather",
    rating: 4.8,
    reviews: 67,
    img: "images/additional/20 chairs/huvudspelare-gaming-chair-black__1039672_pe840417_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 48,
    name: "Krylbo Chair Tonerud Dark Beige",
    category: "office-chairs",
    price: 10900,
    material: "Velvet",
    rating: 4.6,
    reviews: 38,
    img: "images/additional/20 chairs/krylbo-chair-tonerud-dark-beige__1208495_pe908606_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 49,
    name: "Lisabo Chair Ash",
    category: "office-chairs",
    price: 8900,
    material: "Wood",
    rating: 4.5,
    reviews: 24,
    img: "images/additional/20 chairs/lisabo-chair-ash__0786549_pe763015_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 50,
    name: "Lisabo Chair Ash Tallmyra White Black",
    category: "office-chairs",
    price: 12900,
    material: "Wood & Fabric",
    rating: 4.7,
    reviews: 41,
    img: "images/additional/20 chairs/lisabo-chair-ash-tallmyra-white-black__1243660_pe920705_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 51,
    name: "Loberget Malskaer Swivel Chair White",
    category: "office-chairs",
    price: 13900,
    material: "Fabric",
    rating: 4.6,
    reviews: 52,
    img: "images/additional/20 chairs/loberget-malskaer-swivel-chair-white__1078458_pe857202_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 52,
    name: "Marius Stool Black",
    category: "office-chairs",
    price: 3900,
    material: "Metal",
    rating: 4.1,
    reviews: 73,
    img: "images/additional/20 chairs/marius-stool-black__0727386_pe735638_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 53,
    name: "Millberget Swivel Chair Murum Black",
    category: "office-chairs",
    price: 15900,
    material: "Mesh",
    rating: 4.7,
    reviews: 89,
    img: "images/additional/20 chairs/millberget-swivel-chair-murum-black__1020142_pe831799_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 54,
    name: "Renberget Swivel Chair Bomstad Black",
    category: "office-chairs",
    price: 14900,
    material: "Mesh",
    rating: 4.6,
    reviews: 64,
    img: "images/additional/20 chairs/renberget-swivel-chair-bomstad-black__1020135_pe831794_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 55,
    name: "Sandsberg Chair Red Brown",
    category: "office-chairs",
    price: 9900,
    material: "Wood",
    rating: 4.4,
    reviews: 33,
    img: "images/additional/20 chairs/sandsberg-chair-red-brown-remmarn-red-brown__1479094_pe999920_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 56,
    name: "Skalsta Chair Plastic Beige",
    category: "office-chairs",
    price: 6900,
    material: "Plastic",
    rating: 4.0,
    reviews: 48,
    img: "images/additional/20 chairs/skalsta-chair-plastic-beige-tubular-metal-light-gray-beige__1486589_pe1002448_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 57,
    name: "Smaellen Swivel Chair Black",
    category: "office-chairs",
    price: 13500,
    material: "Leatherette",
    rating: 4.5,
    reviews: 71,
    img: "images/additional/20 chairs/smaellen-swivel-chair-black__1096271_pe864278_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 58,
    name: "Teodores Chair White",
    category: "office-chairs",
    price: 7900,
    material: "Plastic",
    rating: 4.3,
    reviews: 29,
    img: "images/additional/20 chairs/teodores-chair-white__0727344_pe735616_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 59,
    name: "Vihals Chair Green Tibbleby Gray Green",
    category: "office-chairs",
    price: 8500,
    material: "Fabric",
    rating: 4.4,
    reviews: 37,
    img: "images/additional/20 chairs/vihals-chair-green-tibbleby-gray-green__1370483_pe958737_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 60,
    name: "Vihals Chair White",
    category: "office-chairs",
    price: 8500,
    material: "Fabric",
    rating: 4.5,
    reviews: 42,
    img: "images/additional/20 chairs/vihals-chair-white__1370478_pe958751_s5.jpg",
    badge: "",
    badgeClass: "",
  },

  // BEDROOM from images/additional/35 beds/ (IDs 61-100)
  {
    id: 61,
    name: "Balestrand Divan Base with Drawer Left Skiftebo Grey",
    category: "bedroom",
    price: 28500,
    material: "Fabric",
    rating: 4.6,
    reviews: 34,
    img: "images/additional/35 beds/balestrand-divan-base-with-drawer-left-skiftebo-grey__0593051_pe674876_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 62,
    name: "Balestrand Divan Bed with 1 Drawer Right Skiftebo Grey",
    category: "bedroom",
    price: 38900,
    material: "Fabric",
    rating: 4.7,
    reviews: 45,
    img: "images/additional/35 beds/balestrand-divan-bed-with-1-drawer-right-skiftebo-grey__0616673_pe687735_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 63,
    name: "Brimnes Bed Frame with Storage and Headboard White Luroey",
    category: "bedroom",
    price: 32500,
    material: "Wood",
    rating: 4.8,
    reviews: 67,
    img: "images/additional/35 beds/brimnes-bed-frame-w-storage-and-headboard-white-luroey__1151032_pe884763_s5.jpg",
    badge: "BEST SELLER",
    badgeClass: "badge-blue",
  },
  {
    id: 64,
    name: "Brimnes Day Bed with 2 Drawers 2 Mattresses White",
    category: "bedroom",
    price: 45900,
    material: "Wood",
    rating: 4.7,
    reviews: 52,
    img: "images/additional/35 beds/brimnes-day-bed-w-2-drawers-2-mattresses-white-afjaell-medium-firm__1161840_pe889557_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  {
    id: 65,
    name: "Gullaberg Bed Frame White",
    category: "bedroom",
    price: 29500,
    material: "Wood",
    rating: 4.5,
    reviews: 28,
    img: "images/additional/35 beds/gullaberg-bed-frame-white__1488529_pe1003369_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  // Continue with all 40 beds...
  
  // DECORATIONS from images/additional/35 decorations/ (IDs 101-140)
  {
    id: 101,
    name: "Aktarport LED String Light Battery White Gray",
    category: "decor",
    price: 2500,
    material: "Plastic",
    rating: 4.6,
    reviews: 89,
    img: "images/additional/35 decorations/akterport-led-string-light-with-40-lights-battery-operated-mini-pompon-white-gray__0957901_pe805147_s5.jpg",
    badge: "",
    badgeClass: "",
  },
  // Continue with all 35 decorations...
  
  // LIGHTING, SOFAS, TABLES will be added in next batches
];

console.log('Loaded', NEW_PRODUCTS_ADDITIONAL.length, 'new products from additional images folder');
